# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4805187aaac91fb10ef4093a16f2fd45e5696b204c34327bc6b78c53fdcde7f1ac655c594ed13522ae71bae2c346af4d187427bf62292dbaed259790c974bccf

test:
  secret_key_base: 4131d53aaa0cbde1b9e396aad2453063bf00d6a624e34f2e33bfcbef8a5752dbb621b0be4dadc969cb216adcb58a02c0177ff5e60e3f7ceed425699d88932bed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
